In [7]:
def dot_product_rep(G, chi1, chi2):
    """
    Find multiplicity of chi1 in chi2, which are characters of G, assumed to be in the order of G.conjugacy_classes()
    
    Parameters:
    -----------
    G group, chi1, chi2 characters of G
    
    Returns:
    --------
    integer
    """
    classes = list(G.conjugacy_classes())
    class_sizes = [G.order() / G.centralizer(C.representative()).order() for C in classes]
    result = 0
    for idx in range(0,len(chi1)):
        result += class_sizes[idx]*chi1[idx]*chi2[idx]
    return result/G.order()


def tensor_rep(chi1,chi2):
    # outputs the character of chi_1 tensored with chi_2
    if (len(chi1) != len(chi2)):
        raise ValueError("characters must have the same length")
    return [chi1[i]*chi2[i] for i in range(0, len(chi1))]

def tensor_power(chi, n):
    # outputs the character chi^n
    return [chi[i]^n for i in range(0, len(chi))]

def perm_char(perms):
    # perms is array of n permutations
    result = [0]*len(perms)
    for i in range(0,len(perms)):
        result[i] = len(Permutation(perms[i]).fixed_points())
    return result


In [11]:
def standard_check(n):
    G = SymmetricGroup(n)
    reps = G.conjugacy_classes_representatives()
    standard_rep = perm_char(reps)
    print(standard_rep)
    chartable = G.character_table()
    # track array of earliest power of V where an irrep appears in
    earliest_occurrences = []
    # print("The standard rep has " + str(len(set(standard_rep))) + " unique values taken by its character.")
    for rep_idx in range(0,chartable.nrows()):
        count = 0
        while (dot_product_rep(G, chartable[rep_idx], tensor_power(standard_rep, count)) == 0):
            print(tensor_power(standard_rep,count),count)
            count += 1
        earliest_occurrences.append(count+1)
    print(chartable)
    return earliest_occurrences

standard_check(4)

[4, 2, 0, 1, 0]
[1, 1, 1, 1, 1] 0
[4, 2, 0, 1, 0] 1
[16, 4, 0, 1, 0] 2
[1, 1, 1, 1, 1] 0
[4, 2, 0, 1, 0] 1
[1, 1, 1, 1, 1] 0
[4, 2, 0, 1, 0] 1
[1, 1, 1, 1, 1] 0
[ 1 -1  1  1 -1]
[ 3 -1 -1  0  1]
[ 2  0  2 -1  0]
[ 3  1 -1  0 -1]
[ 1  1  1  1  1]


[4, 3, 3, 2, 1]

In [12]:
# this checks for all symmetric groups up to a fixed integer (here 25) if any irrep is not contained
# in any of V,V^2,V^3
# have not been able to find any

for n in range(3, 25):
    G = SymmetricGroup(n)
    reps = G.conjugacy_classes_representatives()
    standard_rep = perm_char(reps)
    chartable = G.character_table()
    
    #print(chartable)
    #print("\n")
    # print("The standard rep has " + str(len(set(standard_rep))) + " unique values taken by its character.")
    for rep_idx in range(0,chartable.nrows()):
        count = 0
        while (dot_product_rep(G, chartable[rep_idx], tensor_power(standard_rep, count)) == 0):
            print(chartable[rep_idx,:], tensor_power(standard_rep, count), dot_product_rep(G, chartable[rep_idx], tensor_power(standard_rep, count)))
            count += 1
        #if (count == 2):
        #print(chartable[rep_idx])
        #print("appears in V^" + (count+1).str())
    print("done handling n = " + str(n))

[ 1 -1  1] [1, 1, 1] 0
[ 1 -1  1] [3, 1, 0] 0
[ 2  0 -1] [1, 1, 1] 0
done handling n = 3
[ 1 -1  1  1 -1] [1, 1, 1, 1, 1] 0
[ 1 -1  1  1 -1] [4, 2, 0, 1, 0] 0
[ 1 -1  1  1 -1] [16, 4, 0, 1, 0] 0
[ 3 -1 -1  0  1] [1, 1, 1, 1, 1] 0
[ 3 -1 -1  0  1] [4, 2, 0, 1, 0] 0
[ 2  0  2 -1  0] [1, 1, 1, 1, 1] 0
[ 2  0  2 -1  0] [4, 2, 0, 1, 0] 0
[ 3  1 -1  0 -1] [1, 1, 1, 1, 1] 0
done handling n = 4
[ 1 -1  1  1 -1 -1  1] [1, 1, 1, 1, 1, 1, 1] 0
[ 1 -1  1  1 -1 -1  1] [5, 3, 1, 2, 0, 1, 0] 0
[ 1 -1  1  1 -1 -1  1] [25, 9, 1, 4, 0, 1, 0] 0
[ 1 -1  1  1 -1 -1  1] [125, 27, 1, 8, 0, 1, 0] 0
[ 4 -2  0  1  1  0 -1] [1, 1, 1, 1, 1, 1, 1] 0
[ 4 -2  0  1  1  0 -1] [5, 3, 1, 2, 0, 1, 0] 0
[ 4 -2  0  1  1  0 -1] [25, 9, 1, 4, 0, 1, 0] 0
[ 5 -1  1 -1 -1  1  0] [1, 1, 1, 1, 1, 1, 1] 0
[ 5 -1  1 -1 -1  1  0] [5, 3, 1, 2, 0, 1, 0] 0
[ 5 -1  1 -1 -1  1  0] [25, 9, 1, 4, 0, 1, 0] 0
[ 6  0 -2  0  0  0  1] [1, 1, 1, 1, 1, 1, 1] 0
[ 6  0 -2  0  0  0  1] [5, 3, 1, 2, 0, 1, 0] 0
[ 5  1  1 -1  1 -1  0] [1, 1, 1, 1, 1, 1

KeyboardInterrupt: 

In [18]:
import matplotlib.pyplot as plt
import numpy as np

def plot_standard_check_histogram(n):
    """
    Creates a histogram from the output of standard_check(n)
    
    Parameters:
    n (int): The input for standard_check
    
    Returns:
    None: Displays the histogram plot
    """
    # Get the data from standard_check
    data = standard_check(n)
    
    plt.figure(figsize=(10, 6))
    
    # Create histogram with specific bins for integers 1, 2, 3
    plt.hist(data, bins=[0.5, 1.5, 2.5, 3.5], align='mid', rwidth=0.8)
    
    plt.xlabel('Power of V')
    plt.ylabel('Frequency')
    
    plt.xticks([1, 2, 3])
    
    plt.grid(True, alpha=0.3)
    
    plt.show()

    unique, counts = np.unique(data, return_counts=True)
    print("\nValue counts:")
    for value, count in zip(unique, counts):
        print(f"Value {value}: {count} occurrences ({count/len(data)*100:.1f}%)")


def plot_standard_check_histogram_full(n):
    """
    Creates a histogram from the output of standard_check(n)
    
    Parameters:
    n (int): The input for standard_check
    
    Returns:
    None: Displays the histogram plot
    """
    # Get the data from standard_check
    data = []
    for i in range(1,n):
        data += standard_check(i)
    
    plt.figure(figsize=(10, 6))
    
    # Create histogram with specific bins for integers 1, 2, 3
    plt.hist(data, bins=[, align='mid', rwidth=0.8)
    
    plt.xlabel('Power of V')
    plt.ylabel('Frequency')
    
    plt.xticks(range(1,n))
    
    plt.grid(True, alpha=0.3)
    
    plt.show()
    
    unique, counts = np.unique(data, return_counts=True)
    print("\nValue counts:")
    for value, count in zip(unique, counts):
        print(f"Value {value}: {count} occurrences ({count/len(data)*100:.1f}%)")

plot_standard_check_histogram_full(5)

[1]
[1]
[2, 0]
[1, 1] 0
[ 1 -1]
[ 1  1]
[3, 1, 0]
[1, 1, 1] 0
[3, 1, 0] 1
[1, 1, 1] 0
[ 1 -1  1]
[ 2  0 -1]
[ 1  1  1]
[4, 2, 0, 1, 0]
[1, 1, 1, 1, 1] 0
[4, 2, 0, 1, 0] 1
[16, 4, 0, 1, 0] 2
[1, 1, 1, 1, 1] 0
[4, 2, 0, 1, 0] 1
[1, 1, 1, 1, 1] 0
[4, 2, 0, 1, 0] 1
[1, 1, 1, 1, 1] 0
[ 1 -1  1  1 -1]
[ 3 -1 -1  0  1]
[ 2  0  2 -1  0]
[ 3  1 -1  0 -1]
[ 1  1  1  1  1]


TypeError: unsupported operand type(s) for +: 'range' and 'sage.rings.real_mpfr.RealLiteral'

<Figure size 1000x600 with 0 Axes>